// Extrai as seções de "Descrição dos Níveis" de cada competência
// Run: node scripts/build-rubric.mjs

import { readFileSync, writeFileSync, mkdirSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')

function extractNivelSection(text) {
  // Try to find the scoring levels section
  const markers = [
    'DESCRIÇÃO DOS NÍVEIS',
    'Descrição dos Níveis',
    'DESCRIÇÃO DE NÍVEIS',
    '4. DESCRIÇÃO',
    'Nível 0',
  ]

  let startIdx = -1
  for (const marker of markers) {
    const idx = text.lastIndexOf(marker)
    if (idx !== -1) {
      startIdx = idx
      break
    }
  }

  if (startIdx === -1) startIdx = Math.floor(text.length * 0.6)

  // Also grab the desvios section
  const desviosMarkers = ['3. OS DESVIOS', 'OS DESVIOS', 'Desvios de', 'DESVIOS']
  let desviosIdx = -1
  for (const marker of desviosMarkers) {
    const idx = text.indexOf(marker)
    if (idx !== -1) { desviosIdx = idx; break }
  }

  let rubric = ''
  if (desviosIdx !== -1 && desviosIdx < startIdx) {
    rubric += text.substring(desviosIdx, desviosIdx + 4000) + '\n...\n'
  }
  rubric += text.substring(startIdx, startIdx + 8000)

  return rubric.trim()
}

async function main() {
  mkdirSync(join(root, 'src/lib/ai/refs'), { recursive: true })

  const rubrics = {}

  for (let i = 1; i <= 5; i++) {
    const filePath = join(root, `src/lib/ai/refs/competencia_${i}.txt`)
    const text = readFileSync(filePath, 'utf-8')
    const section = extractNivelSection(text)
    rubrics[i] = section
    writeFileSync(
      join(root, `src/lib/ai/refs/rubric_${i}.txt`),
      section,
      'utf-8'
    )
    console.log(`rubric_${i}.txt: ${Math.round(section.length / 1024)}KB`)
  }

  // Build combined rubric TypeScript module
  const ts = `// AUTO-GENERATED by scripts/build-rubric.mjs
// Contains condensed scoring rubric from official ENEM correction PDFs

${Object.entries(rubrics).map(([i, text]) =>
  `export const RUBRIC_C${i} = ${JSON.stringify(text)}`
).join('\n\n')}

export const ALL_RUBRICS = {
  c1: RUBRIC_C1,
  c2: RUBRIC_C2,
  c3: RUBRIC_C3,
  c4: RUBRIC_C4,
  c5: RUBRIC_C5,
}
`
  writeFileSync(join(root, 'src/lib/ai/refs/rubrics.ts'), ts, 'utf-8')
  console.log('\n✓ src/lib/ai/refs/rubrics.ts gerado')
}

main()
